/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "generador_nonce.v:2" *)
module generador_nonce(clk, reset_L, valid, nonce);
  (* src = "generador_nonce.v:10" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "generador_nonce.v:3" *)
  input clk;
  (* src = "generador_nonce.v:6" *)
  output [7:0] nonce;
  (* src = "generador_nonce.v:4" *)
  input reset_L;
  (* src = "generador_nonce.v:5" *)
  input valid;
  NOT _10_ (
    .A(nonce[0]),
    .Y(_01_)
  );
  NAND _11_ (
    .A(reset_L),
    .B(valid),
    .Y(_02_)
  );
  NOR _12_ (
    .A(_02_),
    .B(_01_),
    .Y(_00_[0])
  );
  NOT _13_ (
    .A(nonce[1]),
    .Y(_03_)
  );
  NOR _14_ (
    .A(_02_),
    .B(_03_),
    .Y(_00_[1])
  );
  NOT _15_ (
    .A(nonce[2]),
    .Y(_04_)
  );
  NOR _16_ (
    .A(_02_),
    .B(_04_),
    .Y(_00_[2])
  );
  NOT _17_ (
    .A(nonce[3]),
    .Y(_05_)
  );
  NOR _18_ (
    .A(_02_),
    .B(_05_),
    .Y(_00_[3])
  );
  NOT _19_ (
    .A(nonce[4]),
    .Y(_06_)
  );
  NOR _20_ (
    .A(_02_),
    .B(_06_),
    .Y(_00_[4])
  );
  NOT _21_ (
    .A(nonce[5]),
    .Y(_07_)
  );
  NOR _22_ (
    .A(_02_),
    .B(_07_),
    .Y(_00_[5])
  );
  NOT _23_ (
    .A(nonce[6]),
    .Y(_08_)
  );
  NOR _24_ (
    .A(_02_),
    .B(_08_),
    .Y(_00_[6])
  );
  NOT _25_ (
    .A(nonce[7]),
    .Y(_09_)
  );
  NOR _26_ (
    .A(_02_),
    .B(_09_),
    .Y(_00_[7])
  );
  DFF _27_ (
    .C(clk),
    .D(_00_[0]),
    .Q(nonce[0])
  );
  DFF _28_ (
    .C(clk),
    .D(_00_[1]),
    .Q(nonce[1])
  );
  DFF _29_ (
    .C(clk),
    .D(_00_[2]),
    .Q(nonce[2])
  );
  DFF _30_ (
    .C(clk),
    .D(_00_[3]),
    .Q(nonce[3])
  );
  DFF _31_ (
    .C(clk),
    .D(_00_[4]),
    .Q(nonce[4])
  );
  DFF _32_ (
    .C(clk),
    .D(_00_[5]),
    .Q(nonce[5])
  );
  DFF _33_ (
    .C(clk),
    .D(_00_[6]),
    .Q(nonce[6])
  );
  DFF _34_ (
    .C(clk),
    .D(_00_[7]),
    .Q(nonce[7])
  );
endmodule
